# Generated by Django 4.2.17 on 2025-01-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(blank=True, max_length=50, null=True)),
                ('pageHeading', models.CharField(blank=True, max_length=50, null=True)),
                ('pageDescription', models.TextField(blank=True, null=True)),
                ('pageBanner', models.FileField(upload_to='services/icons/')),
                ('pageTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('PageMetaDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('PageMetaKeywords', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='services/icons/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dashboard.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentHeading', models.CharField(blank=True, max_length=80, null=True)),
                ('contentDescription', models.TextField()),
                ('contentImage', models.ImageField(upload_to='services/icons/')),
                ('contentButton', models.CharField(blank=True, max_length=200, null=True)),
                ('selectPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pages')),
                ('selectSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.add_section')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
    ]
