# Generated by Django 4.2.16 on 2024-12-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
