# Generated by Django 4.2.17 on 2025-01-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sub_content_subcontentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_content',
            name='contentHeading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contents', to='dashboard.content'),
        ),
    ]
