# Generated by Django 4.2.17 on 2025-01-14 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_about_us_government_home_hr_solutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='costomized_solution_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='customer_satisfaction_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='efficiency_compliance_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='expert_hr_guidance_section_images',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='apostille_services_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='background_checks_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='benefits_management_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='costomized_solution_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='customer_satisfaction_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='document_notarization_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='document_translation_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='efficiency_compliance_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='expert_hr_guidance_section_images',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='fingerprinting_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='payroll_management_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='special_projects_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='staffing_recruitment_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='government',
            name='training_development_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='apostille_services_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='background_checks_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='benefits_management_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='costomized_solution_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='customer_satisfaction_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='document_notarization_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='document_translation_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='efficiency_compliance_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='expert_hr_guidance_section_images',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='fingerprinting_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='payroll_management_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='special_projects_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='staffing_recruitment_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='training_development_buttonImage',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='home',
            name='why_choose_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='hr_solutions',
            name='costomized_solution_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='hr_solutions',
            name='customer_satisfaction_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='hr_solutions',
            name='efficiency_compliance_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='hr_solutions',
            name='expert_hr_guidance_section_images',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='professional_services',
            name='costomized_solution_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='professional_services',
            name='customer_satisfaction_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='professional_services',
            name='efficiency_compliance_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='professional_services',
            name='expert_hr_guidance_section_images',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='professional_services',
            name='why_choose_section_image',
            field=models.FileField(upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
