# Generated by Django 4.2.17 on 2025-01-14 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_about_us_costomized_solution_section_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='help_businesses_build_high_performing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='our_vision_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='our_vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='about_us',
            name='our_vision_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='pagename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='simplify_hr_management_for_businesses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='support_employees_professional_development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='government',
            name='pagename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='pagename',
            field=models.CharField(blank=True, default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='video_button_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='hr_solutions',
            name='pagename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional_services',
            name='pagename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
