# Generated by Django 5.1.4 on 2025-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='description',
            field=models.TextField(help_text='Enter help description'),
        ),
        migrations.AlterField(
            model_name='help',
            name='heading',
            field=models.CharField(help_text='Enter help title', max_length=255),
        ),
    ]
