# Generated by Django 4.2.17 on 2025-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_about_us_recent_government_recent_home_recent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='government',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='help',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='home',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hr_solutions',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='professional_services',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
