# Generated by Django 4.2.17 on 2025-01-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_about_us_original_data_government_original_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Us_Recent',
        ),
        migrations.DeleteModel(
            name='Government_Recent',
        ),
        migrations.DeleteModel(
            name='Home_Recent',
        ),
        migrations.DeleteModel(
            name='Hr_Solutions_Recent',
        ),
        migrations.DeleteModel(
            name='Professional_Services_Recent',
        ),
    ]
