# Generated by Django 4.2.16 on 2024-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
