# Generated by Django 4.2.16 on 2024-12-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cart_service_name_cart_service_price'),
        ('frontend', '0002_alter_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='categoriesList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
    ]
