# Generated by Django 4.2.16 on 2024-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(max_length=20),
        ),
    ]
