# Generated by Django 4.2.17 on 2025-01-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
