# Generated by Django 4.2.17 on 2025-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_order_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='0001', max_length=4, primary_key=True, serialize=False),
        ),
    ]
