# Generated by Django 4.2.17 on 2025-02-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
