# Generated by Django 4.2.17 on 2025-02-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_document_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
